### ISSUE TITLE
My problems

### ISSUE THREAD

**Issue by MarijaRomanenkova** [MarijaRomanenkova/newsongbird#2]
- After using Sass mixin toRem, smt weird is happening to my css, something rewrites particularly these parts, or mixin is not working?

- Did not make it with onKeyDown , wasn't able to make game responsive to keyboard, please advise

**Comment by Viktarrudzenia** [comment]
1. https://dev.to/nikolab/convert-px-to-rem-using-sass-3-methods-4ep2
2. will discuss on call
